samples: "samples.fqpath.tsv"

params:
  trim:
    adapter:  "Linker_Primer_sequence.fa"
    quality:          30
    ao:               5 
    min_length:       150
    cpu:              2
    max_uncalled:     10
    mismatch:         2 
    min_trim_seq:     8
  fq2fa:
    max_err_rate: 0.01
    maxns:        0 
  ninja:
    script:     "./bin/ninja.py"
    db:         "/disk/share/database/greengenes97/greengenes97"
  finaltable:
    cbind_src: "./bin/combine.OTU.R"
    add_src:   "./bin/Add.taxonomy.OTU.py"
    fast_src:  "./bin/fast.py"
    tax_db:    "/disk/share/database/greengenes97/greengenes97.taxonomy"
  rarefy:
    split_src: "./bin/Splice.OTU.table.R"
    cbind_src: "./bin/Combine.OTU.rarefy.R" 

  
result:
  fastqc:      "result/01.fastqc"
  trim:        "result/02.trim"   
  fq2fa:       "result/03.fq2fa"   
  ninja:       "result/04.ninja"
  finaltable:  "result/05.finaltable"
  rarefy:      "result/06.rarefy" 
  multiqc:     "result/07.multiqc"


logs:
  fastqc:      "result/logs/01.fastqc"
  trim:        "result/logs/02.trim"   
  fq2fa:       "result/logs/03.fq2fa"   
  ninja:       "result/logs/04.ninja"
  finaltable:  "result/logs/05.finaltable"
  rarefy:      "result/logs/06.rarefy" 
  multiqc:     "result/logs/07.multiqc"
