samples: "6samples.path.tsv"

params:
  index:
    cpu:  20
    gtf:  "/disk/user/zouhua/pipeline/RNA_seq/database/chr22_with_ERCC92.gtf"
    fa :  "/disk/user/zouhua/pipeline/RNA_seq/database/chr22_with_ERCC92.fa"
  trim:
    adapter:  "/disk/user/zouhua/pipeline/RNA_seq/database/adapter.fa"
    quality:          30
    ao:               5 
    min_length:       99
    cpu:              2
    max_uncalled:     10 
  alignment:
    index:         "/disk/user/zouhua/pipeline/RNA_seq/database/hisat2_index/chr22_with_ERCC92.exon_splice"
    cpu_hisat2:    20
    cpu_samtools:  4
  genecount:
    gtf: "/disk/user/zouhua/pipeline/RNA_seq/database/chr22_with_ERCC92.gtf"
    cpu: 2
  finaltable:
    FPKM : 7
    TPM  : 8
    script : "/disk/user/zouhua/pipeline/RNA_seq/04.hisat2_snakemake/script/combineTable2"

  
result:
  index:       "result/00.index"
  fastqc:      "result/01.fastqc"
  trim:        "result/02.trim"   
  alignment:   "result/03.alignment"   
  genecount:   "result/04.genecount"
  finaltable:  "result/05.finaltable"
  multiqc:     "result/06.multiqc"


logs:
  index:       "result/logs/00.index"
  fastqc:      "result/logs/01.fastqc"
  trim:        "result/logs/02.trim"
  alignment:   "result/logs/03.alignment"
  genecount:   "result/logs/04.genecount"
  finaltable:  "result/logs/05.finaltable"
  multiqc:     "result/logs/06.multiqc"
