samples: "Sample_path.tsv"
filename: "chr22_with_ERCC92"

params:
  trim:
    adapter:     "data/illumina_multiplex.fa"
    min_overlap: 7  
    trim_left:   13
    max_uncall:  300
    min_length:  25
    threads:     4 
  index:
    gtf:        "data/ref.gtf"
    fasta:      "data/ref.fa"
    threads:    4 
  alignment:
    threads1:   4
    threads2:   8
  expression:
    gtf:        "data/ref.gtf"
    threads:    8
    perl:     "scripts/stringtie_expression_matrix.pl"

results:
  quality:        
    fastqc:     "result/00.quality/fastqc"
    multiqc:    "result/00.quality/multiqc"
  trim:         "result/01.trimmed"   
  index:        "result/02.index"   
  alignment:    "result/03.alignment"
  expression:   "result/04.expression"

logs:           "result/logs"

