samples: "6samples.path.tsv"

params:
  index:
    cpu:  20
    gtf:  "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.gtf"
    fa :  "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.fa"  
  trim:
    adapter:  "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/adapter.fa"
    quality:          30
    ao:               5 
    min_length:       80
    cpu:              2
    max_uncalled:     10 
  alignment:
    index:         "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/hisat2_index/chr22_with_ERCC92.exon_splice"
    cpu_hisat2:    10
    cpu_samtools:  4
  genecount:
    gtf: "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.gtf"
    cpu: 2
  finaltable:
    FPKM: 7
    TPM:  8
    script: "/disk/user/zouhua/pipeline/RNAseq/Snakemake_pipeline/script/combineTable2"
    script_count: "/disk/user/zouhua/pipeline/RNAseq/Snakemake_pipeline/script/preDE.py"


result:
  fastqc:      "hisat2_result/01.fastqc"
  trim:        "hisat2_result/02.trim"   
  alignment:   "hisat2_result/03.alignment"   
  genecount:   "hisat2_result/04.genecount"
  finaltable:  "hisat2_result/05.finaltable"
  multiqc:     "hisat2_result/06.multiqc"


logs:
  fastqc:      "hisat2_result/logs/01.fastqc"
  trim:        "hisat2_result/logs/02.trim"
  alignment:   "hisat2_result/logs/03.alignment"
  genecount:   "hisat2_result/logs/04.genecount"
  finaltable:  "hisat2_result/logs/05.finaltable"
  multiqc:     "hisat2_result/logs/06.multiqc"
